# Dockerfile
FROM node:14.19.1
#extra packages for cypress
RUN apt-get update \
    && apt-get install -y libxcursor1 libnss3 libgdk-pixbuf2.0-0 wget \
    libgtk-3-dev libxss-dev libasound2-dev xvfb

WORKDIR /dashboard-ui-docker-dev
COPY ./package.json ./dashboard-ui-docker-dev
COPY . /dashboard-ui-docker-dev
RUN node --max-old-space-size=12388 \
    && yarn install
EXPOSE 3000

ENV HOST 0.0.0.0
ENV NUXT_PORT=3000