const colors = [
  '#a6cee3', '#b2df8a', '#fb9a99', '#fdbf6f', '#cab2d6', '#e18958', '#ff79ca', '#aaa',
  '#1f78b4', '#33a02c', '#e31a1c', '#ff7f00', '#6a3d9a', '#b15928', '#e7298a', '#666',
];

export default () => ({
  loading: false,
  downloading: false,
  error: false,
  cancel: false,
  baseQuery: '',
  query: '',
  queries: [],
  queryKey: null,
  article: null,
  terms: [{text: ''}],
  lastTermAdded: {term: '', index: 0},
  termCounts: {},
  colors: colors,
  articleCount: 0,
  articleList: [],
  articleChunk: [],
  page: 1,
  webEnv: '',
  returnMax: 200,
  returnedCounter: 0,
  gridDefs: [
    // {
    //   filter: false,
    //   suppressSizeToFit: true,
    //   headerCheckboxSelection: true,
    //   headerCheckboxSelectionFilteredOnly: true,
    //   checkboxSelection: true,
    //   sortable: false,
    //   resizable: false,
    //   width: 40,
    //   suppressColumnsToolPanel: true,
    // },
    {
      headerName: '-',
      colId: 'term_0',
      field: 'term_0',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerName: '-',
      colId: 'term_1',
      field: 'term_1',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerName: '-',
      colId: 'term_2',
      field: 'term_2',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerName: '-',
      colId: 'term_3',
      field: 'term_3',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerName: '-',
      colId: 'term_4',
      field: 'term_4',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerName: '-',
      colId: 'term_5',
      field: 'term_5',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerName: '-',
      colId: 'term_6',
      field: 'term_6',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerName: '-',
      colId: 'term_7',
      field: 'term_7',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerName: '-',
      colId: 'term_8',
      field: 'term_8',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerName: '-',
      colId: 'term_9',
      field: 'term_9',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerName: '-',
      colId: 'term_10',
      field: 'term_10',
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      suppressColumnsToolPanel: true,

    },
    {
      headerName: 'Total',
      colId: 'totalCol',
      field: 'totalCol',
      width: 60,
      suppressSizeToFit: true,
      filter: '',
      suppressMenu: true,
      unSortIcon: true,
      hide: true,
      cellClassRules: {totalYellow: 'x>0'},
      suppressColumnsToolPanel: true,
    },
    {
      headerName: 'PubMed ID',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      field: 'pmid',
      width: 100,
      suppressSizeToFit: true,
      filter: '',
      suppressMenu: true,
      cellRenderer: 'pubMedLink',
    },
    {
      headerName: 'Year',
      field: 'year',
      width: 60,
      suppressSizeToFit: true,
      suppressMenu: true,
      floatingFilterComponentParams: {suppressFilterButton: true},
      unSortIcon: true,
    },
    {
      headerName: 'Title',
      field: 'title',
      filter: 'agTextColumnFilter',
      sortable: true,
      unSortIcon: true,
    },
    {
      headerName: 'Authors',
      field: 'authors',
      filter: 'agTextColumnFilter',
      sortable: true,
      unSortIcon: true,
    },
    {
      headerName: 'Journal',
      field: 'journal',
      filter: 'agTextColumnFilter',
      sortable: true,
      unSortIcon: true,
    },
    {
      headerName: 'Review',
      initialWidth: 70,
      field: 'review',
      filter: false,
      resizable: true,
      sortable: true,

      unSortIcon: true,
      suppressMenu: true,
      cellRenderer: 'revCheck',
      cellStyle: {'font-size': '16px'},
    },
    {
      headerName: 'DOI',
      width: 80,
      field: 'doi',
      filter: false,
      sortable: true,
      unSortIcon: true,
      suppressMenu: true,
      cellRenderer: 'doiLink',
    },
    {
      headerName: 'Vol',
      width: 60,
      field: 'volume',
      filter: false,
      sortable: true,
      suppressMenu: true,
      unSortIcon: true,
    },
    {
      headerName: 'Issue',
      width: 60,
      field: 'issue',
      filter: false,
      suppressMenu: true,
      sortable: true,
      unSortIcon: true,
    },
    {
      headerName: 'Pages',
      width: 60,
      field: 'pages',
      filter: false,
      suppressMenu: true,
      sortable: true,
      unSortIcon: true,
    },
  ],
  exportColDefs: [
    {
      header: 'PubMed ID',
      key: 'pmid',
      formatter: 'cellHyperlink',
      formatterParams: {externalLink: 'https://www.ncbi.nlm.nih.gov/pubmed/', useValue: true},
      width: 10,
    }, {
      header: 'Year',
      key: 'year',
    }, {
      header: 'Title',
      key: 'title',
      width: 30,
    }, {
      header: 'Authors',
      key: 'authors',
      width: 30,
    }, {
      header: 'Journal',
      key: 'journal',
      width: 30,
    }, {
      header: 'Review',
      key: 'review',
    }, {
      header: 'DOI',
      key: 'doi',
      formatter: 'cellHyperlink',
      formatterParams: {externalLink: 'https://doi.org/', useValue: true},
      width: 10,
    }, {
      header: 'Volume',
      key: 'volume',
    }, {
      header: 'Issue',
      key: 'issue',
    }, {
      header: 'Pages',
      key: 'pages',
    },
  ],
});

