
const genericValueGetter = value => (Number.isNaN(value) || value === '-' ? value : Number(value).toFixed(2));

const columnDefs = [
  {
    filter: false,
    suppressSizeToFit: true,
    headerCheckboxSelection: true,
    headerCheckboxSelectionFilteredOnly: true,
    checkboxSelection: true,
    sortable: false,
    resizable: false,
    width: 40,
  },
  {
    headerName: 'Sample ID',
    field: 'sampleId',
    tooltipField: 'sampleId',
    suppressMenu: false,
    minWidth: 100,
    width: 110,
  },
  {
    headerName: 'Cell Type',
    field: 'cellType',
    tooltipField: 'cellType',
    suppressMenu: true,
    filter: 'agTextColumnFilter',
    width: 90,
  },
  {
    headerName: 'Seeding Density',
    field: 'seedingDensity',
    floatingFilterComponentParams: {suppressFilterButton: false},
    filter: 'agNumberColumnFilter',
    filterParams: {
      inRangeInclusive: true,
      defaultOption: 'equals',
    },
    suppressMenu: true,
    minWidth: 90,
    width: 1220,
  },
  {
    headerName: 'Exposure Duration (hrs)',
    headerTooltip: 'Exposure Duration measured in hours',
    field: 'exposureDuration',
    floatingFilterComponentParams: {suppressFilterButton: false},
    filter: 'agNumberColumnFilter',
    filterParams: {
      inRangeInclusive: true,
      defaultOption: 'equals',
    },
    suppressMenu: true,
    minWidth: 90,
    width: 1220,
  },
  {
    headerName: 'Endpoint',
    field: 'endpoint',
    tooltipField: 'endpoint',
    width: 90,
    filter: 'agTextColumnFilter',
    sortable: true,
    suppressMenu: true,
    cellStyle: {'white-space': 'normal', 'line-height': '10px'},
    autoHeight: true,
  },
  {
    headerName: 'Endpoint Description',
    field: 'featureNameHarmony',
    minWidth: 130,
    width: 160,
    filter: 'agTextColumnFilter',
    sortable: true,
    cellRenderer: 'PopOverUnderline',
    cellRendererParams: {popField: 'featureNameHarmony', popTextPlacement: 'right'},
    hide: false,
  },
  {
    headerName: 'BMD',
    field: 'bmd',
    floatingFilterComponentParams: {suppressFilterButton: false},
    filter: 'agNumberColumnFilter',
    filterParams: {
      inRangeInclusive: true,
      defaultOption: 'greaterThanOrEqual',
      allowedCharPattern: '\\d\\.\\-',
      filterPlaceholder: (params) => {
      },
    },
    suppressMenu: false,
    width: 75,
    comparator: (num1, num2) => num1 - num2,
    valueGetter: params => genericValueGetter(params.data.bmd),
    cellRenderer: 'numberFieldRenderer',
    cellRendererParams: {fieldName: 'bmd'},
    hide: false,
  },
  {
    headerName: 'Hit Call',
    field: 'hitCall',
    valueGetter: params => genericValueGetter(params.data.hitCall || '-'),
    filter: 'agNumberColumnFilter',
    filterParams: {
      inRangeInclusive: true,
      defaultOption: 'greaterThanOrEqual',
      allowedCharPattern: '\\d\\.\\-',
    },
    floatingFilterComponentParams: {suppressFilterButton: false},
    suppressMenu: true,
    width: 80,
  },
  {
    headerName: 'Top/Cutoff',
    field: 'topOverCutoff',
    floatingFilterComponentParams: {suppressFilterButton: false},
    filter: 'agNumberColumnFilter',
    filterParams: {
      inRangeInclusive: true,
      defaultOption: 'greaterThanOrEqual',
      allowedCharPattern: '\\d\\.\\-',
    },
    suppressMenu: true,
    valueGetter: params => genericValueGetter(params.data.topOverCutoff || '-'),
    minWidth: 90,
    width: 1220,
  },
  {
    headerName: 'Top',
    field: 'topOrig',
    floatingFilterComponentParams: {suppressFilterButton: false},
    filter: 'agNumberColumnFilter',
    filterParams: {
      inRangeInclusive: true,
      defaultOption: 'greaterThanOrEqual',
      allowedCharPattern: '\\d\\.\\-',
    },
    suppressMenu: false,
    valueGetter: params => genericValueGetter(params.data.topOrig || '-'),
    minWidth: 70,
    width: 80,
    headerTooltip: 'Info : Maximum response achieved by the modeled CR curve',
  },
  {
    headerName: 'Cutoff',
    field: 'cutOff',
    floatingFilterComponentParams: {suppressFilterButton: false},
    filter: 'agNumberColumnFilter',
    filterParams: {
      inRangeInclusive: true,
      defaultOption: 'greaterThanOrEqual',
      allowedCharPattern: '\\d\\.\\-',
    },
    suppressMenu: false,
    valueGetter: params => genericValueGetter(params.data.cutOff || '-'),
  },
  {
    headerName: 'QC',
    field: 'qc',
    sortable: true,
    width: 80,
    cellStyle: {'white-space': 'normal', 'line-height': '12px'},
    autoHeight: true,
    valueGetter: p => (!p.data.qc ? '-' : `${(p.data.qc === 'P') ? 'PASS' : 'FAIL'}`),
  },
  {
    headerName: 'QC Flag',
    field: 'qcFlag',
    sortable: true,
    width: 150,
    autoHeight: true,
    cellRenderer: 'QcFlagPopover',
  },
  {
    headerName: 'QC Details',
    field: 'qcPopover',
    sortable: false,
    suppressColumnsToolPanel: true,
    cellStyle: {'white-space': 'normal', 'line-height': '12px'},
    autoHeight: true,
    hide: true,
  },
  {
    headerName: 'Details',
    width: 80,
    field: 'sampleId:',
    colId: 'detailsPopup',
    suppressMenu: true,
    filter: false,
    cellRenderer: 'detailsBtn',
  },
  {
    headerName: 'Plot',
    width: 50,
    filter: false,
    field: 'assayComponentEndpointName',
    colId: 'concRespPlot',
    suppressMenu: true,
    cellRenderer: 'repBtn',
  },
  {
    headerName: 'Channel',
    width: 80,
    field: 'channel',
    tooltipField: 'channel',
    suppressMenu: true,
    filter: 'agTextColumnFilter',
  },
  {
    headerName: 'Module',
    field: 'module',
    tooltipField: 'module',
    filter: 'agTextColumnFilter',
    minWidth: 100,
    width: 120,
  },
  {
    headerName: 'Compartment',
    field: 'compartment',
    colId: 'compartment',
    tooltipField: 'compartment',
    filter: 'agTextColumnFilter',
    suppressMenu: true,
    minWidth: 100,
    width: 120,
  },
  {
    headerName: 'No. Features',
    field: 'numberOfFeature',
    suppressMenu: true,
    floatingFilterComponentParams: {suppressFilterButton: false},
    filter: 'agNumberColumnFilter',
    filterParams: {
      inRangeInclusive: true,
      defaultOption: 'greaterThanOrEqual',
      allowedCharPattern: '\\d\\.\\-',
    },
    minWidth: 100,
    width: 120,
  },
  {
    headerName: 'Fit method',
    field: 'fitMethod',
    floatingFilterComponentParams: {suppressFilterButton: false},
    filter: 'agTextColumnFilter',
    suppressMenu: true,
    minWidth: 100,
    width: 120,
    hide: true,
  },
  {
    headerName: 'Conc',
    field: 'conc',
    colId: 'concentration',
    tooltipField: 'conc',
    suppressMenu: true,
    filter: 'agTextColumnFilter',
    width: 80,
  },
  {
    headerName: 'Response',
    field: 'resp',
    tooltipField: 'resp',
    suppressMenu: true,
    width: 110,
    filter: 'agTextColumnFilter',
  },
  {
    headerName: 'Profile',
    width: 130,
    colId: 'profile',
    cellStyle: {'white-space': 'normal', 'line-height': '20px'},
    wrapText: true,
    autoHeight: true,
    suppressMenu: true,
    hide: true,
  },
];

export default columnDefs;
