const columnDefs = [
  {
    filter: false,
    suppressSizeToFit: true,
    headerCheckboxSelection: true,
    headerCheckboxSelectionFilteredOnly: true,
    checkboxSelection: true,
    sortable: false,
    resizable: false,
    width: 60,
  },
  {
    headerName: 'Source',
    minWidth: 120,
    floatingFilter: true,
    field: 'source',
    filter: 'agTextColumnFilter',
    cellRenderer: 'LinkRenderer',
    cellClass: 'hyperlinks',
    headerClass: 'hide-filter-icon',
    cellRendererParams: params => ({text: params.data.source, url: params.data.recordUrl}),
  },
  // https://jira.epa.gov/browse/CE-4234 - Adding Record URL to CSV Export
  {
    headerName: 'RECORD_URL',
    field: 'recordUrl',
    hide: true,
  },
  {
    headerName: 'Study Type',
    minWidth: 110,
    floatingFilter: true,
    field: 'studyType',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
  },
  {
    headerName: 'Species',
    minWidth: 95,
    floatingFilter: true,
    field: 'species',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
  },
  {
    headerName: 'Strain',
    minWidth: 85,
    floatingFilter: true,
    field: 'strain',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
  },
  {
    headerName: 'Reliability',
    minWidth: 100,
    wrapText: true,
    floatingFilter: true,
    autoHeight: true,
    field: 'reliability',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
    cellClass: 'skin-eye-wrapped',
  },
  {
    headerName: 'Endpoint',
    minWidth: 100,
    wrapText: true,
    autoHeight: true,
    floatingFilter: true,
    field: 'endpoint',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
    cellClass: 'skin-eye-wrapped',
  },
  {
    headerName: 'Score',
    minWidth: 75,
    floatingFilter: true,
    field: 'score',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
  },
  {
    headerName: 'Year',
    minWidth: 75,
    floatingFilter: true,
    field: 'year',
    filter: 'agNumberColumnFilter',
    cellRenderer: 'yearRenderer',
    headerClass: 'hide-filter-icon',
  },
  {
    headerName: 'Guideline',
    minWidth: 175,
    wrapText: true,
    autoHeight: true,
    floatingFilter: true,
    field: 'guideline',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
    cellClass: 'skin-eye-wrapped',
  },
  {
    headerName: 'Classification',
    minWidth: 150,
    wrapText: true,
    autoHeight: true,
    floatingFilter: true,
    field: 'classification',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
    cellClass: 'skin-eye-wrapped',
  },
  {
    headerName: 'Result Text',
    minWidth: 175,
    wrapText: true,
    autoHeight: true,
    floatingFilter: true,
    field: 'resultText',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
    cellClass: 'skin-eye-wrapped',
  },
  {
    headerName: 'GLP',
    minWidth: 125,
    wrapText: true,
    autoHeight: true,
    hide: true,
    floatingFilter: true,
    field: 'glp',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
    cellClass: 'skin-eye-wrapped',
  },
  {
    headerName: 'Authority',
    minWidth: 100,
    wrapText: true,
    autoHeight: true,
    hide: true,
    floatingFilter: true,
    field: 'authority',
    filter: 'agTextColumnFilter',
    headerClass: 'hide-filter-icon',
    cellClass: 'skin-eye-wrapped',
  },
];

export default columnDefs;
