export default () => ({
  gsid: '',
  showAssayDetailsModal: false,
  showActorAssayData: false,
  selectedAssayName: '',
  assays: null,
  assayComponents: [],
  assayData: [],
  assayDataCols: [],
  assayDetails: [],
  categories: [],
  categorySelection: '',
  assayGridDefs: [
    {
      headerName: 'Assay Name',
      field: 'assayName',
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'assayName'},
      autoHeight: true,
      floatingFilter: true,
      flex: 2,
      minWidth: 200,
      maxWidth: 460,
      filter: 'agTextColumnFilter',
    },
    {
      headerName: 'Description',
      flex: 2,
      minWidth: 200,
      maxWidth: 460,
      floatingFilter: true,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'assayDescription'},
      field: 'assayDescription',
      filter: 'agTextColumnFilter',
    },
    {
      field: 'categoryId',
      flex: 1,
      minWidth: 70,
      maxWidth: 80,
      hide: true,
    },
    {
      headerName: 'Assay Data',
      field: 'assayId',
      colId: 'showGridId',
      flex: 1,
      minWidth: 70,
      maxWidth: 80,
      suppressMenu: true,
      cellRenderer: 'AssayDataToggle',
      cellRendererParams: {dataAction: 'assayDataToggle', icon: 'fa-th'},
    },
    {
      headerName: 'Assay Details',
      field: 'assayId',
      colId: 'showModalId',
      flex: 1,
      minWidth: 80,
      maxWidth: 90,
      suppressMenu: true,
      cellRenderer: 'AssayDataToggle',
      cellRendererParams: {dataAction: 'actorDetailsModal', icon: 'fa-file-alt'},
      hide: false,
    },
  ],
  assayDetailsGridDefs: [
    {
      headerName: 'Assay Name',
      field: 'assayName',
      minWidth: 100,
      maxWidth: 300,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'assayName'},
    },
    {
      headerName: 'Assay Description',
      minWidth: 100,
      maxWidth: 350,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'assayDescription'},
      field: 'assayDescription',
      filter: 'agTextColumnFilter',
      hide: false,
    },
    {
      headerName: 'Category',
      field: 'category',
      minWidth: 90,
      maxWidth: 120,
      hide: false,
      suppressMenu: true,
    },
    {
      headerName: '# Components',
      field: 'componentCount',
      minWidth: 50,
      maxWidth: 90,
      hide: false,
      suppressMenu: true,
    },
    {
      headerName: 'Data Collection',
      field: 'dataCollection',
      flex: 2,
      minWidth: 70,
      maxWidth: 120,
      hide: false,
      suppressMenu: true,
    },
    {
      headerName: 'Data Collection Id',
      field: 'dataCollectionId',
      minWidth: 30,
      maxWidth: 60,
      hide: true,
      suppressMenu: true,
    },
    {
      headerName: 'QC Status',
      field: 'qcStatus',
      minWidth: 40,
      maxWidth: 80,
      hide: false,
      suppressMenu: true,
    },
    {
      headerName: 'QC Status ID',
      field: 'qcStatusId',
      flex: 2,
      minWidth: 30,
      maxWidth: 60,
      hide: true,
      suppressMenu: true,
    },
    {
      headerName: 'Source',
      field: 'source',
      flex: 2,
      minWidth: 120,
      maxWidth: 250,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'source'},
      suppressMenu: true,
    },
    {
      headerName: 'Source Id',
      field: 'sourceId',
      flex: 2,
      minWidth: 20,
      maxWidth: 40,
      hide: true,
    },
    {
      headerName: 'species',
      field: 'species',
      flex: 2,
      minWidth: 70,
      maxWidth: 150,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'species'},
      suppressMenu: true,
    },
    {
      headerName: 'species Id',
      field: 'speciesId',
      flex: 2,
      minWidth: 20,
      maxWidth: 40,
      hide: true,
    },
    {
      headerName: 'Substance Count',
      field: 'substanceCount',
      flex: 1,
      minWidth: 80,
      maxWidth: 120,
      suppressMenu: true,
      hide: false,
    },
    {
      headerName: 'Assay Code',
      field: 'assayCode',
      flex: 1,
      minWidth: 100,
      maxWidth: 220,
      suppressMenu: true,
      hide: true,
    },
  ],
  assayComponentsCols: [
    {
      headerName: 'Assay Component Name',
      field: 'assayComponentName',
      minWidth: 100,
      maxWidth: 550,
      tooltipField: 'assayComponentName',
    },
    {
      headerName: 'Description',
      minWidth: 100,
      maxWidth: 550,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'description'},
      field: 'description',
      filter: 'agTextColumnFilter',
      hide: false,
    },
    {
      headerName: 'Component Type',
      field: 'componentType',
      minWidth: 90,
      maxWidth: 200,
      hide: true,
      suppressColumnsToolPanel: true,
      suppressMenu: true,
    },
    {
      headerName: 'Value Type',
      field: 'valueType',
      minWidth: 50,
      maxWidth: 90,
      hide: true,
      suppressMenu: false,
    },
    {
      headerName: 'Source Name',
      field: 'sourceName',
      flex: 2,
      minWidth: 120,
      maxWidth: 150,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'sourceName'},
      suppressMenu: true,
    },
    {
      headerName: 'Source Id',
      field: 'sourceId',
      flex: 2,
      minWidth: 20,
      maxWidth: 40,
      hide: true,
    },
    {
      headerName: 'Assay Id',
      field: 'assayId',
      flex: 2,
      minWidth: 70,
      maxWidth: 100,
      hide: true,
      suppressColumnsToolPanel: true,
      suppressMenu: true,
    },
    {
      headerName: 'Units',
      field: 'units',
      flex: 2,
      minWidth: 60,
      maxWidth: 300,
      hide: false,
    },
  ],
})
