import {ColDef} from 'ag-grid-community';
export const summaryGridDefs: ColDef[] = [
  {
    headerName: 'More',
    colId: 'more',
    field: 'chemicalId',
    width: 45,
    minWidth: 45,
    suppressSizeToFit: true,
    filter: '',
    suppressMenu: true,
    sortable: false,
    cellRenderer: 'moreButton',
    tooltipField: 'chemicalId',
  },
  {
    headerName: 'Source',
    field: 'source',
    headerTooltip: 'Originator of source data',
    width: 110,
    minWidth: 90,
    cellRenderer: 'LinkRenderer',
    cellRendererParams: (params: { data: { source: string; sourceUrl: string; }; }) => ({
      text: params.data?.source,
      url: params.data?.sourceUrl,
    }),
    suppressSizeToFit: true,
  },
  {
    headerName: 'Subsource',
    field: 'subsource',
    tooltipField: 'subsource',
    headerTooltip: 'Originator subgroup of source data',
    width: 110,
    minWidth: 100,
    cellRenderer: 'LinkRenderer',
    cellRendererParams: (params: { data: { subsource: string; subsourceUrl: string; }; }) => ({
      text: params.data?.subsource,
      url: params.data?.subsourceUrl,
    }),
    suppressSizeToFit: true,
  },
  {
    headerName: 'Supercategory',
    field: 'supercategory',
    hide: true,
  },
  {
    headerName: 'Type',
    field: 'toxvalType',
    headerTooltip: 'Effect level type',
    width: 80,
    minWidth: 80,
    tooltipField: 'type',
    filter: 'agTextColumnFilter',
    cellRenderer: 'PopOverUnderline',
    cellRendererParams: {popField: 'definition'},
    sortable: true,
    suppressSizeToFit: true,
  },
  {
    headerName: 'Subtype',
    field: 'toxvalSubtype',
    headerTooltip: 'Effect level subtype',
    width: 90,
    minWidth: 90,
    suppressSizeToFit: true,
    filter: 'agTextColumnFilter',
    cellClass: 'cell-tooltip',
    tooltipField: 'toxvalSubtype',
  },
  {
    headerName: 'Risk Assessment',
    field: 'riskAssessmentClass',
    headerTooltip: 'Media associated with exposure guideline values',
    width: 130,
    minWidth: 100,
    suppressSizeToFit: true,
    filter: 'agTextColumnFilter',
    autoHeight: true,
    wrapText: false,
    cellStyle: {'white-space': 'normal', 'line-height': '18px'},
    cellClass: 'cell-tooltip',
    tooltipField: 'riskAssessmentClass',
  },
  {
    headerName: 'Qualifier',
    suppressMenu: true,
    headerTooltip: 'Qualifier on the effect level',
    field: 'toxvalNumericQualifier',
    tooltipField: 'toxvalNumericQualifier',
    width: 120,
    minWidth: 70,
    filter: false,
    sortable: false,
  },
  {
    headerName: 'Value',
    width: 80,
    minWidth: 80,
    headerTooltip: 'Numeric effect level value',
    field: 'toxvalNumeric',
    filter: 'agNumberColumnFilter',
    tooltipField: 'toxvalNumeric',
    filterParams: {
      inRangeInclusive: true,
    },
    cellRenderer: 'ncctRound2',
    suppressSizeToFit: true,
  },
  {
    headerName: 'Units',
    field: 'toxvalUnits',
    headerTooltip: 'Effect level units',
    tooltipField: 'toxvalUnits',
    maxWidth: 80,
    minWidth: 60,
    suppressMenu: true,
  },
  {
    headerName: 'Study Type',
    field: 'studyType',
    width: 110,
    headerTooltip: 'Study classification scheme for exposure type or effect level type',
    minWidth: 80,
    tooltipField: 'studyType',
  },
  {
    headerName: 'Exposure Route',
    field: 'exposureRoute',
    headerTooltip: 'Exposure route of the test chemical',
    width: 110,
    minWidth: 90,
    tooltipField: 'exposureRoute',
  },
  {
    headerName: 'Effect',
    minWidth: 90,
    width: 140,
    field: 'effect',
    headerTooltip: 'Effect level-associated endpoint or effect',
    suppressSizeToFit: true,
    tooltipField: 'effect',
    autoHeight: true,
    wrapText: false,
    cellStyle: {
      'white-space': 'normal', 'line-height': '18px', wordBreak: 'normal',
    },
  },
  {
    headerName: 'Species',
    headerTooltip: 'Common name for applicable species',
    field: 'speciesCommon',
    width: 110,
    minWidth: 100,
    tooltipField: 'speciesCommon',
  },
  {
    headerName: 'Year',
    width: 110,
    headerTooltip: 'Report or study year',
    minWidth: 70,
    field: 'year',
    tooltipField: 'year',
  },
  {
    headerName: 'Experimental',
    width: 110,
    headerTooltip: 'Flag to indicate experimental study for the test chemical (vs read-across or surrogate values)',
    minWidth: 95,
    field: 'experimental',
    tooltipField:  'experimental',
    wrapText: false,
    cellStyle: {wordBreak: 'normal'},
  },
  {
    headerName: 'Stored Source Record',
    width: 150,
    minWidth: 150,
    headerTooltip: 'Link to associated documents stored on EPA CCTE Clowder repository',
    field: 'stored_source_record',
    tooltipField: 'stored_source_record',
    cellRenderer: 'LinkRenderer',
    cellRendererParams: (params: { data: { stored_source: string; stored_source_record: string; }; }) => ({
      text: params.data?.stored_source_record,
      url: params.data?.stored_source_record,
    }),
    suppressSizeToFit: true,
    wrapText: false,
    cellStyle: {wordBreak: 'normal'},
  },
  {
    headerName: 'QC Level',
    width: 210,
    minWidth: 125,
    field: 'qc_level',
    tooltipField: 'qc_level',
    headerTooltip: 'Categorization system to describe the type of Quality Control (QC) performed. Flags are not hierarchical and are applied at a source and record level',
    wrapText: false,
    cellStyle: {wordBreak: 'normal'},
  },
];

export interface ExportExcelJsColumns {
  header: string;
  key: string;
  width?: number;
  formatter?: string;
  formatterParams?: object
}

export const exportGridDefs: ExportExcelJsColumns[] = [
  {
    header: 'SOURCE',
    key: 'source',
    width: 15,
  },
  {
    header: 'SOURCE_URL',
    key: 'sourceUrl',
    formatter: 'cellHyperlink',
    formatterParams: {linkTitle: 'Source link'},
    width: 15,
  },
  {
    header: 'SUPERCATEGORY',
    key: 'supercategory',
    width: 20,
  },
  {
    header: 'SUBSOURCE',
    key: 'subsource',
    width: 20,
  },
  {
    header: 'SUBSOURCE_URL',
    key: 'subsourceUrl',
    formatter: 'cellHyperlink',
    formatterParams: {linkTitle: 'Subsource link'},
    width: 15,
  },
  {
    header: 'TYPE',
    key: 'toxvalType',
    width: 10,
  },
  {
    header: 'SUBTYPE',
    key: 'toxvalSubtype',
    width: 10,
  },
  {
    header: 'RISK_ASSESSMENT',
    key: 'riskAssessmentClass',
    width: 30,
  },
  {
    header: 'QUALIFIER',
    key: 'toxvalNumericQualifier',
    width: 10,
  },
  {
    header: 'VALUE',
    key: 'toxvalNumeric',
    width: 10,
  },
  {
    header: 'UNITS',
    key: 'toxvalUnits',
    width: 10,
  },
  {
    header: 'STUDY_TYPE',
    key: 'studyType',
    width: 30,
  },
  {
    header: 'STUDY_TYPE_LINK',
    key: 'dtxsid',
    width: 30,
    formatter: 'cellHyperlink',
    formatterParams: {
      route: 'chemical/details/hazard',
      linkLabel: 'Study type',
      useValue: true,
    },
  },
  {
    header: 'EXPOSURE_ROUTE',
    key: 'exposureRoute',
    width: 15,
  },
  {
    header: 'SPECIES',
    key: 'speciesCommon',
    width: 15,
  },
  {
    header: 'EFFECT',
    width: 60,
    key: 'effect',

  },
  {
    header: 'YEAR',
    key: 'year',
    width: 10,
  },
  {
    header: 'EXPERIMENTAL',
    key: 'experimental',
    width: 60,
  },
  {
    header: 'STORED_SOURCE_RECORD',
    key: 'stored_source_record',
    formatter: 'cellHyperlink',
    formatterParams: {linkTitle: 'Stored source record link'},
    width: 60,
  },
  {
    header: 'QC_LEVEL',
    key: 'qc_level',
    width: 60,
  },
];