export default () => ({
  propertyData: {},
  propertySelection: 'SUMMARY',
  summaryGridDefs: [
    {
      headerName: 'Property',
      field: 'property',
      colId: 'property',
      suppressSizeToFit: true,
      width: 170,
      minWidth: 100,
      cellStyle: {
        color: 'rgb(14, 105, 147)', cursor: 'pointer',
      },
    },
    {
      headerName: 'Experimental average',
      width: 100,
      minWidth: 100,
      maxWidth: 200,
      field: 'exavg',
    },
    {
      headerName: 'Predicted average',
      width: 100,
      minWidth: 100,
      maxWidth: 200,
      field: 'predavg',
    },
    {
      headerName: 'Experimental median',
      width: 100,
      minWidth: 100,
      maxWidth: 200,
      field: 'exmedian',
    },
    {
      headerName: 'Predicted median',
      width: 100,
      minWidth: 100,
      maxWidth: 200,
      field: 'predmedian',
    },
    {
      headerName: 'Experimental range',
      width: 100,
      minWidth: 100,
      maxWidth: 200,
      field: 'exrange',
      cellRenderer: 'RangeFormatter',

    },
    {
      headerName: 'Predicted range',
      width: 100,
      minWidth: 100,
      maxWidth: 200,
      field: 'predrange',
      cellRenderer: 'RangeFormatter',
    },
    {
      headerName: 'Unit',
      width: 100,
      minWidth: 100,
      maxWidth: 200,
      field: 'unit',
    },
  ],

  experimentalGridDefs: [
    {
      headerName: 'Source',
      field: 'source',
      flex: 2,
      minWidth: 200,
      maxWidth: 800,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'description'},
      filter: 'agTextColumnFilter',
    },
    {
      headerName: 'Result',
      suppressSizeToFit: true,
      flex: 1,
      minWidth: 100,
      maxWidth: 200,
      field: 'value',
      filter: 'agNumberColumnFilter',
      filterParams: {
        inRangeInclusive: true,
      },
      cellRenderer: 'ncctRound2',
    },
    {
      headerName: 'Experimental Details',
      field: 'experimental_details',
      flex: 2,
      minWidth: 200,
      maxWidth: 800,
      cellRenderer: 'whenEmpty',
      filter: null,
    },
  ],
  predictedGridDefs: [
    {
      headerName: 'Source',
      field: 'source',
      flex: 2,
      minWidth: 200,
      maxWidth: 450,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'description'},
      filter: 'agTextColumnFilter',
    },
    {
      headerName: 'Result',
      field: 'value',
      flex: 1,
      minWidth: 100,
      maxWidth: 150,
      filter: 'agTextColumnFilter',
      cellRenderer: 'ncctRound2',
    },
    {
      headerName: 'Calculation Details',
      field: 'has_opera',
      flex: 2,
      minWidth: 200,
      maxWidth: 550,
      cellRenderer: 'CalculationDetailsRenderer',
      cellRendererParams: {page: 'properties'},
    },
    {
      headerName: 'QMRF',
      field: 'model_id',
      flex: 2,
      minWidth: 200,
      maxWidth: 800,
      cellRenderer: 'qmrfUrl',
    },
  ],
  miniSummaryGridDefs: [
    {
      headerName: 'Type',
      field: 'type',
      flex: 2,
      minWidth: 200,
      maxWidth: 400,
    },
    {
      headerName: 'Average',
      field: 'mean',
      flex: 1,
      minWidth: 100,
      maxWidth: 300,
      cellRenderer: 'ncctRound2',
    },
    {
      headerName: 'Median',
      field: 'median',
      flex: 1,
      minWidth: 100,
      maxWidth: 370,
      cellRenderer: 'ncctRound2',
    },
    {
      headerName: 'Range',
      field: 'range',
      flex: 1,
      minWidth: 200,
      maxWidth: 300,
      cellRenderer: 'RangeFormatter',
    },
    {
      headerName: 'Unit',
      flex: 1,
      minWidth: 200,
      maxWidth: 300,
      field: 'unit',
    },
  ],
});
