export default () => ({
  admeData: {},
  columnDefs: [
    {
      headerName: 'Label',
      field: 'label',
      hide: false,
      minWidth: 120,
      width: 180,
      suppressSizeToFit: true,
      sortable: true,
      filter: true,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'description'},
    },
    {
      headerName: 'Species',
      field: 'species',
      width: 100,
      minWidth: 100,
      sortable: true,
      filter: true,
      floatingFilter: true,
      floatingFilterComponentParams: {suppressFilterButton: false},
      headerClass: 'hide-filter-icon',
      cellRenderer: 'whenEmpty',
    },
    {
      headerName: 'Measured',
      field: 'measured',
      width: 100,
      minWidth: 100,
      sortable: true,
      filter: true,
    },
    {
      headerName: 'Predicted',
      field: 'predicted',
      width: 100,
      minWidth: 100,
      suppressSizeToFit: true,
      sortable: true,
      filter: 'agNumberColumnFilter',
      filterParams: {
        inRangeInclusive: true,
        defaultOption: 'greaterThanOrEqual',
        allowedCharPattern: '\\d\\.\\-',
      },
      // cellRenderer: 'roundTo2',
    },
    {
      headerName: 'Units',
      field: 'unit',
      width: 120,
      minWidth: 100,
      sortable: true,
      filter: true,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'unit'},
    },
    {
      headerName: 'Model',
      headerTooltip: 'computational model used',
      field: 'model',
      width: 120,
      minWidth: 100,
      sortable: true,
      filter: true,
      floatingFilter: true,
      headerClass: 'hide-filter-icon',
      cellRenderer: 'whenEmpty',
    },
    {
      headerName: 'Percentile',
      headerTooltip: 'indicates which predicted steady-state plasma concentration percentile was calculated',
      field: 'percentile',
      width: 100,
      minWidth: 100,
      sortable: true,
      filter: true,
      floatingFilter: true,
      headerClass: 'hide-filter-icon',
      cellRenderer: 'whenEmpty',
    },
    {
      headerName: 'Reference',
      headerTooltip: 'reference for measured or predicted value. Full references: https://rdrr.io/cran/httk/man/chem.physical_and_invitro.data.html',
      field: 'reference',
      minWidth: 100,
      width: 120,
      sortable: true,
      filter: true,
      cellRenderer: 'PopOverUnderline',
      cellRendererParams: {popField: 'reference'},
    },
    {
      headerName: 'Data Source Species',
      headerTooltip: 'data source used for the predictions',
      field: 'dataSourceSpecies',
      width: 130,
      minWidth: 100,
      sortable: true,
      filter: true,
      cellRenderer: 'whenEmpty',
    },
    {
      field: 'orderBy',
      hide: true,
      sort: 'asc',
      suppressColumnsToolPanel: true,
    },
    {
      field: 'dtxsid',
      hide: true,
      sort: 'asc',
    },
  ],
});
